version: 0.2         
env:
  variables:
     S3_BUCKET: sam-package-availability
phases:
  install:
    commands:
      - cd app && npm install && cd ../
  pre_build:
    commands:
      - cd app
      - node_modules/.bin/eslint .
      - cd ..
  build: 
    commands:
      - cd app
      - npm run test
      - cd ..

artifacts:
    type: zip 
    files:
      - '**/*'
